# Data Skills (Individual) {#ch1_data_skills}

In this Chapter, we have included information about the Data Skills Assessments in RM2 (ANOVA and Regression). You can use the menu at the right hand side of this page to jump to the different sections.

## General Information

-   Deadlines for this assessment can be found under 'Deadlines' within the 'Course Information' section on the RM2 Moodle.

-   In total this assessment is worth 10% of your final course grade. Each data skills worksheet is worth 5% and you will be awarded a mark out of 22.

-   The submission links (and where appropriate, files) will be made available at least one week before the deadline.

## Important information about R submissions (please read and watch the video!)

Please note the following for the R submissions:

-   you must use the R markdown file provided. If you submit a file that you made yourself, the submission will automatically receive an H.

-   you must not alter the R chunk itself (e.g. adding/removing backticks, removing or altering t0x etc.) in the R markdown file. If you do, you will automatically receive an H for that question and it may result in an H for the whole assessment.

-   you must submit the completed .Rmd file. If you submit a blank .Rmd file, your submission will automatically receive an H.

-   you must not alter the name of the object that the task is asking you to create

Please see [this video](https://uofglasgow.zoom.us/rec/play/kGPffSDx2RT741ZEXDG28KaYFxRDyriV1cO-Tmy0VDcWEDn_2wcCeX853_1t8T9jzrOzEfxMFcgu6yCt.zBN1JhinbBQSRjzG?eagerLoadZvaPages=&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&startTime=1725965232000&componentName=rec-play&originRequestUrl=https%3A%2F%2Fuofglasgow.zoom.us%2Frec%2Fshare%2FC7w5EqVNPod9aLKY4SwMtW67PhxNwBaS1GXjvRrOwvVffKGB3HqNler6at6ESWzP.eiXr0xmkpri2n-VX%3FstartTime%3D1725965232000){target="_blank"} for further details.

## Type of Assessment/Structure

-   You will be provided with an .Rmd file that you should complete and submit, like the homeworks you did in RM1. Some questions are dependent on each other, but most are independent.

-   Both worksheets have 19 questions each. Some questions are worth 1 point and some are worth 2 points. You can see how much each task is worth on the worksheet.

-   The points on each worksheet will total to 22.

-   You will be presented with three types of questions: error mode, code writing and multiple choice

-   For **error mode**, instead of asking you to write the code yourself, we're going to provide you with code that has errors in it. This code will either not run and it will produce an error message, or it will run, but it won't produce what it is supposed to. In both cases you have to fix the code to produce the intended output. The purpose of these tasks is to resolve errors and learn to debug, so please don't ask on Teams about the errors you get on the error mode tasks.

-   For **code writing**, you will be given instructions on code that you should write. Provide the code that gives exactly the intended output (and only that). For some questions, you will be provided a data frame or a plot in the instructions file, and you will be asked to recreate that in the task. You should replace the NULL in the code chunk with your code.

-   For **multiple choice**, you will be asked questions about the data or interpreting your statistical output. Please replace the NULL in the code chunk with the number of the option you think is correct. Please only use a single number, do not use words, and do not put the number in quotation marks.

## Assessment Support

-   Most of the tasks are based on code and functions you have seen in the data skills book

-   Each worksheet has a couple of questions on things you may not have seen before. This is either to use a new function, or to combine functions in a new way. These tasks are there to test your generalisation skills with R functions.

-   You can find instructions for how to complete the .Rmd files in the data skills book

-   For the multiple choice questions about interpreting statistical output, you may also need to revise some of the key concepts from your lectures.

-   Further information about feedback can be found in [the Feedback Section of this chapter](#data_skills_feedback)

## How to do well in this Assessment

-   Use the data skills activities to guide you.

-   Read the question carefully and ensure that you provide exactly what is asked for (e.g., code or a single value), and only that.

-   Follow the instructions for how to fill out the .Rmd file carefully making sure you do not change anything in the file you shouldn't.

-   Ensure you are up to date with the R activities, as the data skills activities will assess your knowledge of these.

-   Before you submit, make sure that your .Rmd file knits -- if it does it means that what you have written is legal code (this is not to say that you will have written the correct code, it simply means you definitely haven't written any code that doesn't work).

## Common Mistakes

-   Changing the .Rmd file other than to provide answers and your GUID (e.g., deleting backticks, changing code chunk names, not using the file provided).

-   Failure to follow instructions (e.g., writing code when a single value was requested).

-   Including any illegal code in your .Rmd file, e.g., install.packages (you should never write code that would change something on someone else's machine, it causes issues and it's impolite!).

-   Changing object names

## How is the assessment related to the lectures for this course?

-   The data skills submissions assess your ability to wrangle and visualise data in an open and reproducible way, as discussed in the lectures.

-   Some tasks test your ability to interpret statistical test output.

## Why am I being assessed like this?

-   The worksheets assess your ability to wrangle and analyse data in a reproducible way. These are important skills for psychological researchers to develop.

-   Your skills in data skills will progress throughout your degree and the worksheets ensure that you are maintaining a good rate of progress so that you are prepared for your dissertation.

## How does this relate to previous work I have completed?

-   The feedback from your RM1 data skills worksheets will be useful for these submissions.

-   In addition, the guidance and solutions in the data skills book, posting on Teams and attending office hours will help you complete this assessment.

## Academic intergrity

Please note that when submitting your work for assessment we accept it on the understanding that it is your own effort and work and unique to the set assignment.

To support you in understanding what plagiarism is and in avoiding it, please read the following resources that the University provides:

-   [SRC Advice and Support](https://www.glasgowunisrc.org/advice/){target="_blank"}
-   [Code of Student Conduct](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2025-26/feesandgeneral/studentsupportandconductmatters/reg33/){target="_blank"} and [Plagiarism & Academic Integrity Code](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2025-26/feesandgeneral/studentsupportandconductmatters/reg32/){target="_blank"}
-   [Avoiding plagiarism and engage in good academic practice](https://moodle.gla.ac.uk/course/view.php?id=13038){target="_blank"} (a Moodle course you can self-enrol in)
-   [Student support for AI, plagiarism and digital skills](https://www.gla.ac.uk/myglasgow/sld/){target="_blank"}

**In summary:**

All work submitted by students for assessment is accepted on the understanding that it is the student's own effort. This means students' work should not contain:

-   plagiarised content; or
-   content that has been produced by another person, website, software or Artificial intelligence (AI) tool (except where AI use is explicitly permitted); or
-   content that has been prepared jointly with any other person (except where this is explicitly permitted); or
-   content that has already been submitted for assessment by the student at this or any other institution, known as self-plagiarism.

**Statement on groupwork:** We encourage students to form a study group and peer feedback groups. However, this assignment is not a group work assignment, so your work must be your own individual contribution. If you make a study group or a peer review group, avoid sharing final drafts or near final drafts of your work.

**University statement on AI:** The University of Glasgow recognises the value of generative artificial intelligence (AI) tools in academic and professional workplaces.The university has a responsibility to ensure that students acquire the necessary knowledge, skills, and other competencies associated within their discipline. The Student Learning Development service provides general guidance and support for students on the use of generative AI. Each item of assessment in your courses will have specific guidance about the use of AI. Where generative AI restrictions are in place, they have been carefully designed to maximise your learning opportunity whilst discouraging reliance on generative AI in a way that undermines your learning or development of good professional practice and graduate attributes.

**Statement on use of generative AI:** The current assessment is summative, meaning that it contributes to your course grade. **The purpose of this assessment is to develop and practice coding skills and data analysis. You can use AI as a learning assistant to explain code, to understand error messages and help documentation, and as a rubber duck to help articulate problems**. If you want to use translation software (i.e., code in another language first) be cautious as the syntax produced by generative AI is not always in keeping with the current coding language and can result in incorrect answers.

**Avoid using AI to write your code as you risk not fully understanding the analysis and so you fail to build a foundation for future coding/analysis tasks. Avoid using AI to write comments for your code, as commenting helps you to articulate what you did and also helps you to understand the analysis and results more deeply.**

There is no expectation that you will use generative AI, and we have no evidence that its use will confer an advantage for this assessment. If you do use generative AI, you MUST acknowledge use in-text via citations and referencing and in an appendix with a declaration of AI use as appropriate. If you choose to use it, we recommend that you use the Microsoft Edge Browser with Copilot and sign in with your university account using the multi-factor authentication to ensure that your work is private and secure. **Please keep a log of your use of AI as we may ask to see this.**

For this assignment, we will consider it a misuse of generative AI if you do not acknowledge using it. Declare all uses of AI, including initial exploration of the subject, literature searching, writing and editing, corrections for grammar and spelling, as well as any other tasks from the course. Be aware that AI may not represent the best response for this task, and you need to take responsibility for everything that is submitted.

## Feedback {#data_skills_feedback}

### How is this assessment graded?

-   Each worksheet will have 19 questions. Each question will be worth 1 or 2 points, with all questions adding up to 22 points for each worksheet.

-   The computer-assisted marking code that we use checks that the objects in each code chunk are identical to the solution. It is therefore crucial that you follow the instructions carefully and do not change the names of the objects or the code chunks. These instructions are clearly stated in the submission files and you will lose marks if you provide the correct code but change the names.

### How will the feedback from assessment help me in the future?

-   This assessment will help you in any future work that requires working with quantitative data such as your dissertation project or future postgraduate courses.

-   Additionally, R can be used for tasks such as conducting text analyses and building websites and therefore is an extremely useful transferable skill.

### What feedback will I receive for this assessment?

-   You will get a feedback sheet for each data skills worksheet that tells you your score for each question and the correct solution.

-   There will be additional generic feedback provided for questions with common mistakes and to explain the answers if necessary beyond the solution.

-   Finally, there will be individual feedback for any incorrect answers as necessary.

### Who assessed my work?

-   The worksheets will be graded using computer-assisted marking. In the first instance, the marking will be done automatically using R and then any incorrect answers will be checked manually.

### Can I get more feedback?

-   Yes! We encourage you discuss your assessment (regardless of the grade you received) with Wilhelmiina Toivo, who is in charge of marking this assessment.

-   You can do so by attending her office hours, or contacting her directly to arrange an appointment if you cannot make the office hours.

### What if I don't agree with my feedback or grade?

-   Your first point of contact should be to arrange an additional feedback meeting with the course lead.

-   Following this, if you still have concerns you should consult [the guidance from the SRC](https://www.glasgowunisrc.org/advice/academic/appeals/){target="_blank"} which provides a clear explanation of the University appeals procedures. There are only three grounds for appeal:

    -   Unfair or defective procedure
    -   Failure to take into account medical or other adverse personal circumstances
    -   There are relevant medical or other adverse personal circumstances which for good reason have not previously been presented.

You cannot appeal against academic judgement.
