---
title: "Qualitative Portfolio (Group)"
editor: visual
---

In this Chapter, we have included information about the Qualitative Portfolio in RM2. You can use the menu at the right hand side of this page to jump to the different sections.

## General Information

-   The deadline for this assessment can be found under 'Deadlines' within the 'Course Information' section on the RM2 Moodle.

-   This is a group assessment, with each group typically consisting of around 4-6 students.

-   The qualitative portfolio consists of three activities that should be completed and submitted in your groups.

-   This assessment is worth 30% of your final course grade and will be a group mark.

-   One member of your group should submit your portfolio to Moodle by the deadline.

-   The submission link will open no later than 5 working days before the deadline and will be found in the Assignment Submission section of Moodle.

## Word Count and Formatting

-   The maximum word count for the qualitative portfolio is 1000 words. The word limit includes all written aspects, including any additional headings and in-text citations for Activities 1B, 2 and 3. However, it does not include the qualitative questions for Activity 1A and your reference list. There is no 10% rule, 1000 words is a strict upper limit.

-   Please use the template provided for the portfolio.

-   Your work should be presented in Times New Roman, 12-point font, double-spaced with 1-inch (2.54cm) margins.

-   Your submission should be written and formatted according to APA 7th guidelines.

## Type of Assessment/Structure

-   This assessment will be a group and collaborative submission. Please note that there is a single mark for each submission, which will consist of three separate sections. All group members will receive the same mark for the submission. Sections will not, under any circumstances, be considered separately. Therefore it is vital that **all members of the group read and agree on the whole submission beforehand.**

-   The portfolio will consist of a) developing questions for qualitative research, and reflecting on these, b) an ethics exercise, and c) identifying issues in a recording of a focus group.

-   For this assessment, you will be required to:

    -   follow the guidance for each of the three sections, ensuring that you complete the tasks as directed
    -   reflect on the issues presented in the materials, considering how to mitigate them
    -   link to the literature base and ethical guidelines, helping to support your points.

## Intended Learning Outcomes (ILOs)

Below, we have the ILOs for this assessment. Please note that some of the ILOs are over-arching (i.e. apply to all three sections) whereas others are specifically for a single section. To increase clarity, we have stated which section/s apply for each ILO.

1.  Quality of the Knowledge and Research

    -   Develop six questions that would be likely to generate open discussion and rich responses from participants (#1: Qual questions)
    -   Correctly identify ONE ethical issue, explain its importance, and provide guidance on how to mitigate it (#2: Ethics)
    -   Correctly identify TWO or THREE issues present in the focus group, explain why they are problematic, and discuss possible improvements (#3: Focus group)

2.  Quality of the Evaluation

    -   As appropriate for each section, use academic evidence and/or reference to ethical guidelines to support your evaluation (#1: Qual questions, #2 Ethics, #3: Focus group)
    -   As appropriate for each section, demonstrate understanding of the practical issues of running qualitative research through evaluation and reflection (#1: Qual questions, #2 Ethics, #3: Focus group)
    -   As appropriate for each section, synthesise academic evidence from multiple perspectives to demonstrate critical thinking and to support your position (#1 Qual questions, #2 Ethics, #3 Focus group)

3.  Quality of the Academic Communication

    -   Write clearly and succinctly with appropriate use of paragraphs, spelling and grammar, following APA 7th guidelines for tall citations and references (#1: Qual questions, #2 Ethics, #3: Focus group)

*Please note: In the first bullet point under ILO 2 (Quality of the Evaluation), we are not asking for you to relate to ethical guidelines for each section. We are asking you to link to academic evidence/ethical guidelines (as appropriate) for each of the three sections.*

## Assessment Support

-   Guidance on how to complete the group portfolio will be provided as part of the course. These will be released on Moodle, but you will also be able to find all key resources in the Group Project Chapter **(ADD LINK)**.

-   Further information about feedback can be found in the Feedback section **(ADD LINK)**

-   Additional writing and study advice, including 1-to-1 guidance from [Student Learning Development](https://www.gla.ac.uk/myglasgow/sld/){target="_blank"}

-   FAQs from previous students can be found in the FAQs Chapter **(ADD LINK)**

## How to do well in this assessment

-   Meet each of the intended learning outcomes - use these as a checklist for your work.

-   Consult the guidelines provided closely, as these will provide key information about what is required in this assessment.

-   Identify the key points in the literature that are relevant to each task, and relate them to your study.

-   **Task 1: Qual questions** Develop qualitative questions that are open, clear, concise and appropriate. Take into account whether you are designing them for an interview, focus group or survey and use relevant evidence in your reflection.

-   **Task 2 Ethics** Remember to link your identified ethics issue to the BPS code of Ethics.

-   **Task 3: Focus Group** Make sure to use evidence to support your discussion on your chosen issues. Follow the guidelines on how many issues to discuss.

-   Allow time to proof-read your work before submission.

-   Work as a group and make sure everybody reads and agrees on the final submission.

## Common Mistakes

-   Developing questions that are closed, inappropriate, rambling or ask multiple different questions at once.

-   Not linking to the evidence base in your written response.

-   Not following the guidance provided for the assessment.

-   Not following the guidance on how many ethical/focus group issues to discuss.

-   Providing reflections that are shallow.

-   Writing that is unclear and/or vague.

-   Failure to adhere to the overall word limit.

-   Not following the suggested word counts for each activity.

-   Splitting sections among members of the group and not then considering the submission as a coherent whole. It is important to remember that all members should approve the full submission beforehand.

## How is the assessment related to the lectures for this course?

-   The qualitative portfolio allows you the opportunity to apply many of the concepts that you will learn about in more detail in the lectures.

-   It will help give you insight to some of the practical issues related with conducting qualitative research, and considering how you might address these.

## Why am I being assessed like this?

-   Completing the qualitative portfolio is very important for a) better understanding how to conduct qualitative research practically, b) giving an understanding of the processes that underlie the data you will use for your qualitative report. These are key steps to your project, and help form a strong foundation.

-   The qualitative portfolio is a group submission to reflect the fact that in most research, these decisions will be made as a team and it allows you to pool your collective knowledge to design the best study possible. Group work is an essential part of requirements for the British Psychological Society, and is a key part of this course.

## How does this relate to previous work I have completed?

-   You can gain informal feedback by posting on Teams, attending student office hours and attending the course leads Q&A session.

-   Feedback on any previous written assignment will help with academic communication and using evidence to support your arguments.

Feedback on your Stage 1 and Stage 2 reports for RM1 will help you with how you link to the evidence base in your evaluation.

## Academic integrity

Please note that when submitting your work for assessment we accept it on the understanding that it is your own effort and work and unique to the set assignment.

To support you in understanding what plagiarism is and in avoiding it, please read the following resources that the University provides:

-   [SRC Advice and Support](https://www.glasgowunisrc.org/advice/){.external target="_blank"}
-   [Code of Student Conduct](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2025-26/feesandgeneral/studentsupportandconductmatters/reg33/){.external target="_blank"} and [Plagiarism & Academic Integrity Code](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2025-26/feesandgeneral/studentsupportandconductmatters/reg32/){.external target="_blank"}
-   [Avoiding plagiarism and engage in good academic practice](https://moodle.gla.ac.uk/course/view.php?id=13038){.external target="_blank"} (a Moodle course you can self-enrol in)
-   [Student support for AI, plagiarism and digital skills](https://www.gla.ac.uk/myglasgow/sld/){.external target="_blank"}

**In summary:**

All work submitted by students for assessment is accepted on the understanding that it is the student's own effort. This means students' work should not contain:

-   plagiarised content; or
-   content that has been produced by another person, website, software or Artificial intelligence (AI) tool (except where AI use is explicitly permitted); or
-   content that has been prepared jointly with any other person (except where this is explicitly permitted); or
-   content that has already been submitted for assessment by the student at this or any other institution, known as self-plagiarism.

**Statement on groupwork:** This is a group assignment and one person from the group should be nominated to submit the final version of the assignment on Moodle. Your group's work should not be exactly the same as that of another group in the class, however, as you worked closely from common templates, we know that there may be some unavoidable similarities.

**University statement on AI:** The University of Glasgow recognises the value of generative artificial intelligence (AI) tools in academic and professional workplaces.The university has a responsibility to ensure that students acquire the necessary knowledge, skills, and other competencies associated within their discipline. The Student Learning Development service provides general guidance and support for students on the use of generative AI. Each item of assessment in your courses will have specific guidance about the use of AI. Where generative AI restrictions are in place, they have been carefully designed to maximise your learning opportunity whilst discouraging reliance on generative AI in a way that undermines your learning or development of good professional practice and graduate attributes.

**Statement on use of generative AI:** The current assessment is summative, meaning that it contributes to your course grade. **The purpose of this assessment is to provide an opportunity to develop your writing and communication. You can use AI as a learning assistant to help understand lecture content, to give feedback on your work, and to help in finding spelling and grammatical errors.** If you want to use translation software (i.e., you write the assignment in another language first) be cautious as the vocabulary and syntax produced by generative AI is not generally in keeping with the current language use and vocabulary in our field and can result in subtle misunderstanding in communication.

**Avoid using AI to draft your assignment or structure your work, as these are specialist skills that you need to practice. Avoid using AI to make your citations or reference section, as there is a risk that it will fabricate information.**

There is no expectation that you will use generative AI, and we have no evidence that its use will confer an advantage for this assessment. If you do use generative AI, you MUST acknowledge use in-text via citations and referencing and in an appendix with a declaration of AI use as appropriate. If you choose to use it, we recommend that you use the Microsoft Edge Browser with Copilot and sign in with your university account using the multi-factor authentication to ensure that your work is private and secure. **Please keep a log of your use of AI as we may ask to see this.**

For this assignment, we will consider it a misuse of generative AI if you do not acknowledge using it. Declare all uses of AI, including initial exploration of the subject, literature searching, writing and editing, corrections for grammar and spelling, as well as any other tasks from the course. Be aware that AI may not represent the best response for this task, and you need to take responsibility for everything that is submitted.

## Feedback

### What type of feedback will I receive for this assessment?

-   You will receive written on-script comments, as well as three actionable feed-forward suggestions for work in the future (e.g. your qual report, your dissertation).

-   You will also receive a rating on each of the expanded ILOs.

### Can I get more feedback?

-   If you would like to discuss your mark and feedback you should contact your marker, however, **we ask that you wait 24 hours after the release of the grades** before you do so to give you time to fully reflect on the feedback given.

You can arrange a meeting with your marker to clarify your grades and feedback but it can also be the case that you understand everything that was written and you just want a bit more feedback, or you'd like to chat about the essay generally. Please do make use of the opportunity to talk with your marker because it really does make a difference.

To help the discussion, when you e-mail your marker, you must complete [the feedback reflection form](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EanCqf_RV7pMumQt1Bm0N4YB3RlzoIjP9kmbe0qbYj9rYQ?e=MDWxPP){target="_blank"} which will ask you to consider the below:

-   Confirm that you read the following feedback:
    -   All on-script comments
    -   Any feed-forward comments
    -   The ratings on the ILOs
-   Whether there was any feedback you did not understand or agree with.
-   Whether you think your feedback aligned with your grade. If not, we ask for an explanation.
-   Whether there is any aspect of your work you would like more feedback on.

### How is this assessment graded?

-   We use the [Schedule A marking criteria](https://www.gla.ac.uk/media/Media_1200302_smxx.pdf){target="_blank"}, marking each assessment on a 22-point scale.

-   We use the Intended Learning Outcomes **ADD LINK** presented above to mark this assessment.

### How will feedback from this assessment help me in the future?

-   Primarily, the feedback (and feedforward) obtained will support the write-up of your RM2 report. It will also be relevant for your dissertation in Year 3.

-   Additionally, the feedback will help in any future research work you conduct that requires qualitative data collection, qualitative analysis, and evidence-based justification.

### Who assessed my work?

-   The first marker for this assessment will be a member of the RM2 staff team.

-   Following University's policy, your assessment may be second marked by another member of the RM2 team. A range of work from across all markers will be second marked, to ensure that we are applying appropriate standards in assessment and that they are being applied consistently across the cohort of students being assessed.

### What if I don't agree with my feedback or grade?

-   Your first point of contact should be to arrange an additional feedback meeting with the marker of the report (the name will have been provided in your feedback). It is most likely to be either Ashley or Wil who will have marked this assessment. This meeting should be to gain additional feedback from the marker, rather than to contest the grade.

-   Following this, if you still have concerns, you should consult [the guidance from the SRC](https://www.glasgowunisrc.org/advice/academic/appeals/){target="_blank"} which provides a clear explanation of the University appeals procedures. There are only three grounds for appeal:

    -   Unfair or Defective Procedure
    -   Failure to take into account medical or other adverse personal circumstances
    -   There are relevant medical or other adverse personal circumstances which for good reason have not previously been presented.

It is not possible to appeal against academic judgement.
