# Qualitative Report (Individual) {#ch4_AIS_report}

In this Chapter, we have included information about the Qualitative Report in RM2. You can use the menu at the right hand side of this page to jump to the different sections.

## General Information

-   The deadline for this assessment can be found under 'Deadlines' within the 'Course Information' section on the RM2 Moodle.

-   There are different topics for this assessment, and you should choose ONE of these. These will be released by course leads at the beginning of Semester 2.

-   This is an individual submission. We ask for the following documents to be submitted as **separate** documents:

    -   the qualitative report (including references and appendices)
    -   the step-by step analysis template

-   This assessment is worth 50% of your final course grade.

-   The submission link will open no later than 5 working days before the deadline and will be found in the Assignment Submission section of the RM2 Moodle.

## Word Count and Formatting

-   The maximum word count for the report is 3000 words. This includes all aspects of the report with the exception of the reference list and appendices. There is no 10% rule, 3000 words is a strict upper limit.

-   Your work should be presented in Times New Roman, 12-point font, double-spaced with 1-inch (2.54cm) margins.

-   All aspects of your report should be written and formatted according to APA guidelines.

## Intended Learning Outcomes {#report_ILOs} 

1.  Quality of the Knowledge and Research

    -   Provide a comprehensive review of literature, which synthesises the main ideas and contextualises key issues.
    -   Clearly justify the aims of the project
    -   Clearly and correctly report the methods of the study

2.  Quality of the Evaluation

    -   Evaluate your role and positionality as a researcher in shaping the research process.
    -   Clearly present themes and interpret them within a narrative. Ensure these are supported by verbatim evidence from the transcript.
    -   Evaluate your study and how your results fit into the wider literature and social/psychological context.
    -   Identify relevant methodological limitations, implications, and future directions in the context of previous research.

3.  Quality of the Academic Communication

    -   Write clearly and succinctly with appropriate use of paragraphs, spelling and grammar. Ensure that all parts of the report have a logical structure. Ensure that the report follows APA style consistently.
    -   Clearly support ideas and statements with appropriate citations.
    -   Clearly and transparently record the analytical process. Upload the separate submission containing your reflexive diary and each stage of analysis.

## Assessment Support

-   Guidance on how to complete the qualitative report will be provided as part of the course. These will be released on Moodle, but you will also be able to find all key resources in [the Qualitative Report Chapter](#ch12_qualitative_report).

-   Further information about feedback can be found in [the Feedback section](#report_feedback)

-   Additional writing and study advice, including 1-to-1 guidance from [Student Learning Development](https://www.gla.ac.uk/myglasgow/sld/){target="_blank"}

-   FAQs from previous students can be found in [the FAQs Chapter](#faqs)

## How to do well in this assessment

-   Meet each of the intended learning outcomes - use these as a checklist for your work.

-   Write clearly, concisely, with an academic tone and logical structure.

-   Provide an evidence-based rationale for your research question(s), AND an evidence base for the use of qualitative methods.

-   Narrow the focus of the literature review to a specific topic (for example, not a general review of all the literature on disabled people's experiences).

-   Be clear about who the participants in your sample is and why this is relevant in relation to previous research.

-   Engage with qualitative research! Read some of the articles in the reading list, or qualitative research in your topic of interest.

-   Be ethical - do not share sensitive information or anything that might identify your participants. The quotes and transcript that you share must be appropriate for the audience (i.e. markers, examiners, fellow students).

-   Keep the method section brief. Saying that, refer to materials (e.g. focus group schedules) that are placed in the appendices.

-   In the analysis, focus on two main themes OR one main theme and two sub-themes. Describe each theme clearly and explain the themes using quotes as evidence.

-   In the analysis the narrative goes beyond pure description and identifies underlying themes (e.g., contrasting different viewpoints, conflicting emotions, identity).

-   Evaluation of findings in relation to previous research demonstrates a clear link between the introduction and discussion.

-   Produce a professional document by proof reading the entire report.

-   Provide a concise conclusion and an overall summary that covers each section of the report in the form of an abstract.

-   Adhere to APA conventions for referencing and formatting.

## Common Mistakes

-   Vague or general statements as to why the project is utilising qualitative methods.

-   Broad review of the topic area which lacks focus.

-   Basing the rationale for the report upon personal opinion or "common knowledge" rather than peer-reviewed evidence.

-   Missing detail and/or unnecessary detail in the method section.

-   Fragmented analysis with no coherent narrative.

-   Broad or overly descriptive analysis.

-   A lack of evaluation of the literature in relation to the project findings, and/or a discussion of the limitations that is not supported by evidence.

-   Evaluation of findings using quantitative, rather than qualitative, terminology (e.g., hypotheses validity, generalisation).

-   Writing that contains grammatical errors, a lack of clarity, or an informal tone.

-   Failure to adhere to the word limit.

## How is the assessment related to the lectures for the course?

-   The qualitative project assesses your ability to apply your knowledge of qualitative research methods from the lectures and using this in a practical context. This will allow you to develop skills in qualitative research design and analytical techniques.

-   Depending on the exact topic you choose, the project may also be related to content from our lectures across the rest of the Conversion course.

## Why am I being assessed like this?

-   The assessment reflects the structure of a qualitative research article and is an example of the format used in this area to report qualitative research and is relevant dissertations using qualitative methods.

-   The qualitative project will help you with future reports you write (whether they are qualitative or not), including your dissertation.

## How does this relate to previous work I have completed?

-   Research Methods 2 trains you to design, conduct and write up research reports. Although the use of qualitative research method in this assessment is new, you have already completed work that requires evidence-based writing, critical analysis, and clear and concise communication.

-   You have already completed a report in RM1, and -- although this was quantitative -- it's similar in overall structure, and therefore the feedback received from this will help support this assessment.

-   Feedback from the group portfolio assessment will also help you with the report in terms of evaluation, academic communication and writing skills.

-   Feedback on any written assignment will help with academic communication.

## Academic integrity

Please note that when submitting your work for assessment we accept it on the understanding that it is your own effort and work and unique to the set assignment.

To support you in understanding what plagiarism is and in avoiding it, please read the following resources that the University provides:

-   [SRC Advice and Support](https://www.glasgowunisrc.org/advice/){target="_blank"}
-   [Code of Student Conduct](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2025-26/feesandgeneral/studentsupportandconductmatters/reg33/){target="_blank"} and [Plagiarism & Academic Integrity Code](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2025-26/feesandgeneral/studentsupportandconductmatters/reg32/){target="_blank"}
-   [Avoiding plagiarism and engage in good academic practice](https://moodle.gla.ac.uk/course/view.php?id=13038){target="_blank"} (a Moodle course you can self-enrol in)
-   [Student support for AI, plagiarism and digital skills](https://www.gla.ac.uk/myglasgow/sld/){target="_blank"}

**In summary:**

All work submitted by students for assessment is accepted on the understanding that it is the student's own effort. This means students' work should not contain:

-   plagiarised content; or
-   content that has been produced by another person, website, software or Artificial intelligence (AI) tool (except where AI use is explicitly permitted); or
-   content that has been prepared jointly with any other person (except where this is explicitly permitted); or
-   content that has already been submitted for assessment by the student at this or any other institution, known as self-plagiarism.

**Statement on groupwork:** This report is not a group work assignment, so your work must be your own individual contribution. However, as you worked closely in a small team and from common templates, we know that there may be some unavoidable similarities between team members in the methods and results, but it should never be identical or close to identical.

**University statement on AI:** The University of Glasgow recognises the value of generative artificial intelligence (AI) tools in academic and professional workplaces.The university has a responsibility to ensure that students acquire the necessary knowledge, skills, and other competencies associated within their discipline. The Student Learning Development service provides general guidance and support for students on the use of generative AI. Each item of assessment in your courses will have specific guidance about the use of AI. Where generative AI restrictions are in place, they have been carefully designed to maximise your learning opportunity whilst discouraging reliance on generative AI in a way that undermines your learning or development of good professional practice and graduate attributes.

**Statement on use of generative AI:** The current assessment is summative, meaning that it contributes to your course grade. **The purpose of this assessment is to provide an opportunity to complete a qualitative analysis and write it up as a research report. You can use AI as a learning assistant to help understand lecture content, to give feedback on your work, and to help in finding spelling and grammatical errors.** If you want to use translation software (i.e., you write the assignment in another language first) be cautious as the vocabulary and syntax produced by generative AI is not generally in keeping with the current language use and vocabulary in our field and can result in subtle misunderstanding in communication.

**Avoid using AI to draft your assignment or structure your work, as these are specialist skills that you need to practice. Avoid using AI to make your citations or reference section, as there is a risk that it will fabricate information. Avoid using AI to do coding or generating themes in your qualitative analysis, for three reasons: 1) there are ethical issues as participants in the research datasets have not approved their data being loaded to GenAI, 2) the output generated tends to be of poor quality on its own, and 3) you need to practice these skills so you can develop them.**

There is no expectation that you will use generative AI, and we have no evidence that its use will confer an advantage for this assessment. If you do use generative AI, you MUST acknowledge use in-text via citations and referencing and in an appendix with a declaration of AI use as appropriate. If you choose to use it, we recommend that you use the Microsoft Edge Browser with Copilot and sign in with your university account using the multi-factor authentication to ensure that your work is private and secure. **Please keep a log of your use of AI as we may ask to see this.**

For this assignment, we will consider it a misuse of generative AI if you do not acknowledge using it. Declare all uses of AI, including initial exploration of the subject, literature searching, writing and editing, corrections for grammar and spelling, as well as any other tasks from the course. Be aware that AI may not represent the best response for this task, and you need to take responsibility for everything that is submitted.

## Feedback {#report_feedback}

### What type of feedback will I receive for this assessment?

-   You will receive written on-script comments, as well as three actionable feed-forward suggestions for your dissertation.

-   You will also receive a rating on each of the expanded ILOs.

### Can I get more feedback?

-   If you would like to discuss your mark and feedback you should contact your marker, however, **we ask that you wait 24 hours after the release of the grades** before you do so to give you time to fully reflect on the feedback given.

You can arrange a meeting with your marker to clarify your grades and feedback but it can also be the case that you understand everything that was written and you just want a bit more feedback, or you'd like to chat about the essay generally. Please do make use of the opportunity to talk with your marker because it really does make a difference.

To help the discussion, when you e-mail your marker, you must complete [the feedback reflection form](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EanCqf_RV7pMumQt1Bm0N4YB3RlzoIjP9kmbe0qbYj9rYQ?e=MDWxPP){target="_blank"} which will ask you to consider the below:

-   Confirm that you read the following feedback:
    -   All on-script comments
    -   Any feed-forward comments
    -   The ratings on the ILOs
-   Whether there was any feedback you did not understand or agree with.
-   Whether you think your feedback aligned with your grade. If not, we ask for an explanation.
-   Whether there is any aspect of your work you would like more feedback on.

### How is this assessment graded?

-   We use the [Schedule A marking criteria](https://www.gla.ac.uk/media/Media_1200302_smxx.pdf){target="_blank"}, marking each assessment on a 22-point scale.

-   We use [the Intended Learning Outcomes presented above](#report_ILOs) to mark this assessment.

### How will feedback from this assessment help me in the future?

-   Primarily, the feedback (and feedforward) obtained will support the write-up of your dissertation.

-   Additionally, the feedback will help in any future research work you conduct that requires qualitative data collection, qualitative analysis, and evidence-based justification.

### Who assessed my work?

-   The first marker for this assessment will be a member of the RM2 staff team.

-   Following University's policy, your assessment may be second marked by another member of the RM2 team. A range of work from across all markers will be second marked, to ensure that we are applying appropriate standards in assessment and that they are being applied consistently across the cohort of students being assessed.

### What if I don't agree with my feedback or grade?

-   Your first point of contact should be to arrange an additional feedback meeting with the marker of the report (the name will have been provided in your feedback). This meeting should be to gain additional feedback from the marker, rather than to contest the grade. If this does not bring a resolution, please reach out to the course lead/s in the first instance.

-   Following this, if you still have concerns, you should consult [the guidance from the SRC](https://www.glasgowunisrc.org/advice/academic/appeals/){target="_blank"} which provides a clear explanation of the University appeals procedures. There are only three grounds for appeal:

    -   Unfair or Defective Procedure
    -   Failure to take into account medical or other adverse personal circumstances
    -   There are relevant medical or other adverse personal circumstances which for good reason have not previously been presented.

It is not possible to appeal against academic judgement.
