lang: en
project:
  type: book
  output-dir: docs
  resources: resources
execute:
  freeze: auto
book:
  title: RM2 ODL Qualitative Project Resources
  subtitle: ''
  author: Ashley Robertson & Wil Toivo
  doi: ''
  license: CC-BY
  description: This book contains resources for the qualitative project in Research Methods 2 ODL
  cover-image: images/logos/logo1.png
  image: images/logos/logo1.png
  favicon: images/logos/logo1.png
  cookie-consent: false
  google-analytics: ''
  page-navigation: true
  search: true
  downloads:
  - pdf
  - epub
  sharing:
  - twitter
  - facebook
  - linkedin
  sidebar:
    title: ''
    logo: ''
    search: true
    contents: ''
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 3
    pinned: true
    header: ''
    footer: ''
  margin-header: ''
  page-footer:  CC-BY (2025) Ashley Robertson & Wil Toivo
  chapters:
  - index.qmd
  - 01_Assessment_information.qmd
  - 02_Qualitative_designs.qmd
  - 03_Qualitative_questions.qmd
  - 04_Data_collection.qmd
  - 05_Data_analysis.qmd
  - 06_UsingNVivo.qmd
  - 07_Ethics_rigour_reflexivity.qmd
  - 08_Group_project.qmd
  - 09_Academic_writing.qmd
  - 10_Qualitative_report.qmd
  - 11_FAQs.qmd
  appendices:
  - appendix_a_showcase.qmd
  - appendix_b_employability.qmd
bibliography: include/references.bib
csl: include/apa.csl
format:
  html:
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-copy: hover
    highlight-style: a11y
    mainfont: ''
    monofont: ''
    include-after-body:
    - include/webex.js
    - include/script.js
