# Qualitative Research Showcases 

Throughout RM2, we will showcase some exciting qualitative research which will go beyond what you are taught on the course. For each showcase, we'll provide a couple of research papers for you to look at. You don't need to read these in full (unless you find it interesting and want to!) - the purpose is to give you a little taster of the multifaceted and creative things that can be achieved with qualitative methods.  We hope that you find these papers interesting! 

## Qualitative research showcase 1 - Alternative data collection methods

On RM2, we mainly focus on "standard" data collection methodologies (interviews, focus groups, qualitative surveys), but much of published qualitative research uses more creative methods, such as art-based approaches (music or photo elicitation, storytelling, collages, etc.), participant-provided diaries, or data scraping. Arts-based approaches allow for data collection which is less formal than an interview/focus group situation might be and they give the participant space to express themselves more freely. Diary studies allow for data collection over time without overburdening the participants, while data scraping is very sueful when working with sensitive topics and/or minority populations that are hard to reach or overburdened by research participation requests. 

- Dr Gail Prasad's study explores children's views of plurilingualism through collage-creation. [Access the study](https://www.tandfonline.com/doi/full/10.1080/13670050.2017.1420033){target="_blank"}
- Dr December-Maxwell and colleagues investigate involuntary celibacy through Reddit data. [Access the study](https://link.springer.com/article/10.1007/s12119-020-09724-6){target="_blank"}

**Dissertation hint:** Data scraping from Reddit (this can be done with R) has been used in previous dissertation projects where primary data collection would be too difficult due to the topic/population, or where a student has wanted to work with secondary data but the topic doesn't have open data available in research databases - keep this in mind for next year!


## Qualitative Research Showcase 2 - Participatory Research

Participatory research refers to the involvement of the groups that are affected by the issue that is being studied. It is becoming increasingly more utilised in qualitative research, and it is considered good practice particularly in the areas where the studied group is disadvantaged or marginalised. The underlying philosophy of participatory research is to see the people studied not as "subjects" to research, but actively participating stakeholders. 

- Drs Vaughn and Jacquez have written an excellent review of the different types and core principles of participatory research. [Access the article](https://jprm.scholasticahq.com/article/13244-participatory-research-methods-choice-points-in-the-research-process){target="_blank"}
- Drs Yaros and Schueller conducted a study on positive computing technologies for children with children as co-creators of the research. [Access the article](https://www.jmir.org/2017/1/e14/){target="_blank"}
- Dr Crompton and colleagues studied peer support of autistic young adults in schools with a research team that directly involves autistic stakeholders. Pay particular attention to the Community Involvement section of the article. [Access the article](https://journals.sagepub.com/doi/full/10.1177/13623613221081189){target="_blank"}

**Dissertation hint:** If you want to work with marginalised or disadvantaged populations for your dissertation, have a conversation early on with your supervisor about how you might want to incorporate participatory elements into your study. Due to the limited timescale, for dissertations this often looks less fully fledged than what you would see in published papers. For example, for a dissertation, the researcher student might have lived experience themselves, or they might reach out to University networks to find a person with lived experience to review the research question and/or analysis. 


## Qualitative Research Showcase 3 - Interesting Analysis Methods

In this qualitative research showcase, we highlight a couple of different types of analyses to give a (very small!) snapshot of the variety of qualitative techniques. Please bear in mind these are beyond what is expected from you on RM2 - don't try to apply these analyses to your report. 

- Dr Wilson and colleagues conducted a meta-synthesis of qualitative studies on older adulthood. This is a way to bring together findings from multiple qualitative studies - have a look and see what differences and similarities between this and quantitative meta-analysis. [Access the article](https://www.cambridge.org/core/journals/ageing-and-society/article/abs/developing-a-model-of-resilience-in-older-adulthood-a-qualitative-metasynthesis/AE8457482A9371FF74F391E97E43800F){target="_blank"}
- Drs Goodman and Burke conducted a discourse analysis on attitudes to immigrants. Compare and contrast how the analysis is presented and how the quotes are used as opposed to a Thematic Analysis. [Access the paper](https://journals.sagepub.com/doi/abs/10.1177/0957926509360743){target="_blank"}

**Dissertation hint:** If you are doing a qualitative dissertation, most supervisors will encourage you to do Thematic Analysis because it's highly structured and there is a lot of guidance available. If you are interested in more advanced qualitative analyses, make sure that you have a discussion about this when talking to potential supervisors to identify whether they support this.
